import type { Produto } from "./types";

/**
 * Cardápio real da loja (preços informados pela Di Minas).
 * Serve de conteúdo enquanto o Supabase não está configurado e de carga
 * inicial do banco — ver scripts/schema.sql.
 */
export const produtosIniciais: Produto[] = [
  // Pães de queijo recheados
  {
    id: "frango-tradicional",
    nome: "Frango Tradicional",
    descricao: "Frango desfiado no tempero da casa, Catupiry e vinagrete fresco.",
    preco: 25.9,
    unidade: "unidade",
    categoria: "recheados",
    foto_url: "/fotos/pao-de-queijo-colagem.jpeg",
    disponivel: true,
    pronta_entrega: true,
    destaque: false,
    ordem: 1,
  },
  {
    id: "frango-tudo",
    nome: "Frango Tudo",
    descricao:
      "Frango desfiado, Catupiry, vinagrete, milho, azeitona, calabresa, bacon e muçarela. O mais pedido da casa.",
    preco: 34.9,
    unidade: "unidade",
    categoria: "recheados",
    foto_url: "/fotos/pao-de-queijo-recheado.jpeg",
    disponivel: true,
    pronta_entrega: true,
    destaque: true,
    ordem: 2,
  },
  {
    id: "pernil-tradicional",
    nome: "Pernil Tradicional",
    descricao: "Pernil suculento desfiado, Catupiry e vinagrete fresco.",
    preco: 27.9,
    unidade: "unidade",
    categoria: "recheados",
    foto_url: "/fotos/pao-de-queijo-recheado-3.jpeg",
    disponivel: true,
    pronta_entrega: true,
    destaque: false,
    ordem: 3,
  },
  {
    id: "pernil-tudo",
    nome: "Pernil Tudo",
    descricao:
      "Pernil suculento desfiado, Catupiry, vinagrete, bacon, milho, azeitona, muçarela e calabresa.",
    preco: 36.9,
    unidade: "unidade",
    categoria: "recheados",
    foto_url: "/fotos/pao-de-queijo-recheado-2.jpeg",
    disponivel: true,
    pronta_entrega: true,
    destaque: false,
    ordem: 4,
  },

  // Combos
  {
    id: "combo-1",
    nome: "Combo 1",
    descricao: "Um pão de queijo Frango Tudo e um Guaraná Antarctica em lata, normal ou zero.",
    preco: 39.9,
    unidade: "combo",
    categoria: "combos",
    foto_url: "/fotos/combo-1.jpeg",
    disponivel: true,
    pronta_entrega: true,
    destaque: false,
    ordem: 5,
  },
  {
    id: "combo-2",
    nome: "Combo 2",
    descricao: "Um pão de queijo Pernil Tudo e um Guaraná Antarctica em lata, normal ou zero.",
    preco: 41.9,
    unidade: "combo",
    categoria: "combos",
    foto_url: "/fotos/combo-2.jpeg",
    disponivel: true,
    pronta_entrega: true,
    destaque: false,
    ordem: 6,
  },
  {
    id: "combo-casal",
    nome: "Combo Casal",
    descricao: "Dois pães de queijo Frango Tudo e dois Guaraná Antarctica em lata, normal ou zero.",
    preco: 79.9,
    unidade: "combo",
    categoria: "combos",
    foto_url: "/fotos/combo-casal.jpeg",
    disponivel: true,
    pronta_entrega: true,
    destaque: false,
    ordem: 7,
  },

  // Doces de leite
  {
    id: "doce-de-leite-tradicional",
    nome: "Doce de Leite Tradicional",
    descricao: "Cremoso e suave, no ponto de colher. Perfeito para acompanhar o cafezinho passado.",
    preco: 39.9,
    unidade: "pote de 450 g",
    categoria: "doces",
    foto_url: "/fotos/doce-de-leite.jpeg",
    disponivel: true,
    pronta_entrega: true,
    destaque: true,
    ordem: 8,
  },
  {
    id: "doce-de-leite-flavors",
    nome: "Doce de Leite Flavors",
    descricao:
      "A base cremosa da casa com pedaços de frutas, castanhas e texturas especiais. Sabores: nozes, morango, coco, chocolate, café, damasco e ameixa — consulte os do dia.",
    preco: 45.9,
    unidade: "pote de 450 g",
    categoria: "doces",
    foto_url: "/fotos/produtos-mineiros.jpeg",
    disponivel: true,
    pronta_entrega: true,
    destaque: false,
    ordem: 9,
  },

  // Congelados
  {
    id: "congelado-1kg",
    nome: "Pão de Queijo Premium Congelado",
    descricao:
      "Tamanho coquetel, cerca de 40 g por unidade. Rende de 24 a 25 unidades do mesmo sabor da Canastra.",
    preco: 45.9,
    unidade: "pacote de 1 kg",
    categoria: "congelados",
    foto_url: "/fotos/pao-de-queijo-tradicional.jpeg",
    disponivel: true,
    pronta_entrega: true,
    destaque: true,
    ordem: 10,
  },

  // Pães
  {
    id: "pao-caseiro",
    nome: "Pão Caseiro Tradicional",
    descricao: "Feito de forma artesanal, com aquele sabor de pão quentinho que lembra casa de vó.",
    preco: 19.9,
    unidade: "unidade",
    categoria: "paes",
    foto_url: "/fotos/paes-caseiros.jpeg",
    disponivel: true,
    pronta_entrega: false,
    destaque: false,
    ordem: 11,
  },

  // Bebidas
  {
    id: "coca-cola",
    nome: "Coca-Cola ou Coca-Cola Zero",
    descricao: "Lata gelada.",
    preco: 9.0,
    unidade: "lata",
    categoria: "bebidas",
    foto_url: "/fotos/bebidas.jpeg",
    disponivel: true,
    pronta_entrega: true,
    destaque: false,
    ordem: 12,
  },
  {
    id: "guarana",
    nome: "Guaraná Antarctica ou Guaraná Zero",
    descricao: "Lata gelada.",
    preco: 8.5,
    unidade: "lata",
    categoria: "bebidas",
    foto_url: null,
    disponivel: true,
    pronta_entrega: true,
    destaque: false,
    ordem: 13,
  },
  {
    id: "agua-com-gas",
    nome: "Água com Gás Cristal",
    descricao: null,
    preco: 5.0,
    unidade: "garrafa",
    categoria: "bebidas",
    foto_url: null,
    disponivel: true,
    pronta_entrega: true,
    destaque: false,
    ordem: 14,
  },

  // Adicionais
  { id: "add-milho", nome: "Milho", descricao: null, preco: 2.0, unidade: "porção", categoria: "adicionais", foto_url: null, disponivel: true, pronta_entrega: true, destaque: false, ordem: 15 },
  { id: "add-azeitona", nome: "Azeitona", descricao: null, preco: 2.0, unidade: "porção", categoria: "adicionais", foto_url: null, disponivel: true, pronta_entrega: true, destaque: false, ordem: 16 },
  { id: "add-mucarela", nome: "Muçarela", descricao: null, preco: 2.0, unidade: "porção", categoria: "adicionais", foto_url: null, disponivel: true, pronta_entrega: true, destaque: false, ordem: 17 },
  { id: "add-calabresa", nome: "Calabresa", descricao: null, preco: 3.0, unidade: "porção", categoria: "adicionais", foto_url: null, disponivel: true, pronta_entrega: true, destaque: false, ordem: 18 },
  { id: "add-bacon", nome: "Bacon", descricao: null, preco: 4.5, unidade: "porção", categoria: "adicionais", foto_url: null, disponivel: true, pronta_entrega: true, destaque: false, ordem: 19 },
  { id: "add-catupiry", nome: "Catupiry extra", descricao: null, preco: 4.0, unidade: "porção", categoria: "adicionais", foto_url: null, disponivel: true, pronta_entrega: true, destaque: false, ordem: 20 },
];
